version: "3.9"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5500:5000"
    volumes:
      - ./mlflow_server/mlruns:/mlflow/mlruns    # artifact storage
      - ./mlflow_server/data:/mlflow/data        # SQLite DB folder
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/data/mlflow.db
      --host 0.0.0.0
      --port 5000
    user: root

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    user: root
    restart: always

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: front-end
    ports:
      - "80:80"
    user: root
    restart: always
