version: "3.9"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5500:5000"
    volumes:
      - ./mlflow_server/mlruns:/mlflow/mlruns    # artifact storage
      - ./mlflow_server/data:/mlflow/data        # SQLite DB folder
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/data/mlflow.db
      --host 0.0.0.0
      --port 5000
    user: root

